version: '3'

services:
  db:
    image: fl-db
  redis:
    image: redis
    ports:
      - "6379:6379"
  api:
    image: fl-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/fl-api/api
  client:
      image: fl-client
      ports:
        - "80:80"


