version: '3'

services:
  db:
    image: fl-db
  api:
    image: fl-api
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
      image: fl-client
      ports:
        - "80:80"

